version: 2.1

orbs:
  python: circleci/python@0.2.1


jobs:
  build-and-push:
    executor: python/default
    steps:
      - add_ssh_keys
      - checkout
      - run: 
          command: |
            git clone https://github.com/burukuru/Flex
            pipenv install pelican markdown ghp-import
            pipenv run pelican
            git config user.email "ci-build@thanhpham.cloud"
            git config user.name "ci-build"
            pipenv run ghp-import output -m "[skip ci] Update website" -b master -p

workflows:
  main:
    jobs:
      - build-and-push:
        filters:
          branches:
            only:
             - pelican
