version: 2.1

orbs:
  python: circleci/python@0.2.1


jobs:
  build-and-push:
    executor: python/default
    steps:
      - add_ssh_keys
      - checkout
      - run: 
          command: |
            git clone https://github.com/burukuru/Flex
            pipenv install pelican
            pipenv run pelican -s pelicanconf.py
            git clone git@github.com:burukuru/burukuru.github.io.git master
            cp -avr output/* master
            cd master
            git commit -a -m 'Update website'
            git push
workflows:
  main:
    jobs:
      - build-and-push:
        filters:
          branches:
            only:
             - pelican
